name: Build and Release - DEBUG

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Fix paths for Gradle
        run: |
          mkdir -p android/node_modules
          # Копируем критические зависимости для автолинкинга
          cp -r node_modules/@react-native android/node_modules/ || true
          cp -r node_modules/expo-modules-autolinking android/node_modules/ || true

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace --info