import json
import os

# Base English translations as reference
base_en = {
    "common": {"loading": "Loading…", "error": "Error", "cancel": "Cancel", "ok": "OK", "delete": "Delete", "save": "Save"},
    "status": {"idle": "Ready", "thinking": "Thinking…", "error": "Error"},
    "agentStatus": {"modelNotSet": "Model not set", "connectionNotConfigured": "Connection not configured", "keySet": "key set", "noKey": "no key", "messages": "msgs"},
    "fileManager": {"previewTruncated": "\n\n[Preview truncated: showing first {{count}} characters.]", "attachTruncated": "\n\n[File truncated when attaching: first {{count}} characters sent.]", "folderReadError": "Failed to read folder", "bigFileTitle": "Large file", "bigFilePreview": "File {{size}}. Only the beginning will be shown for preview.", "unsupportedFile": "Unsupported file", "notUtf8": "File could not be read as UTF-8 text.", "fileReadError": "Failed to read file", "fileOpenError": "Failed to open file", "binaryNotSupported": "Binary files cannot be attached as text.", "bigFileAttach": "File {{size}}. Only a shortened text version will be attached.", "notUtf8Attach": "File could not be read as UTF-8 text, so it will not be attached.", "attachReadError": "Failed to read file for attachment", "deleteTitle": "Delete", "deleteConfirm": "Delete «{{name}}»?", "cancel": "Cancel", "delete": "Delete", "deleteError": "Failed to delete", "appData": "App data", "downloads": "Downloads", "photos": "Photos", "documents": "Documents", "files": "Files", "searchPlaceholder": "Search files...", "folderEmpty": "Folder is empty"},
    "settings": {"language": "Language", "model": "Model", "apiFormat": "API Format", "connection": "CONNECTION", "provider": "Provider", "custom": "Custom", "noKey": "No key", "token": "Token", "keyOptional": "Key (optional)", "loading": "Loading…", "endpointHint1": "Leave empty if endpoint does not require a key.", "endpointHint2": "Authorization token for this provider.", "endpointHint3": "Leave empty if no authorization is required.", "permissions": "PERMISSIONS", "contactsAccess": "Assistant contacts access", "contactsHint": "Even when enabled, calls and SMS require separate confirmation.", "androidPermissions": "Android permissions", "checkingPermissions": "Checking permissions…", "stats": "STATISTICS", "inputTokens": "input", "outputTokens": "output", "totalTokens": "total", "requests": "requests", "usageChart": "Usage chart", "resetStatsButton": "Reset statistics", "update": "UPDATE", "currentVersion": "Current version", "updateHint": "Argus · Checks GitHub releases", "checkingUpdates": "Checking for updates…", "checkUpdates": "Check for updates", "updateAvailable": "Update available", "downloadInstall": "Download and install", "downloading": "Loading…", "apkDownloaded": "APK downloaded. Open the file to install.", "retry": "Retry", "skills": "SKILLS", "noSkills": "No saved skills", "skillsHint": "Skills are created automatically when AI solves complex tasks.", "usedCount": "used {{count}} times", "settingsTitle": "Settings", "resetStatsTitle": "Reset statistics", "resetStatsMessage": "Reset token counters?", "resetStatsConfirm": "Reset", "noUpdates": "No updates", "noUpdatesHint": "You have the latest version.", "checkError": "Check error", "downloadError": "Download error", "permissionTitle": "Permission", "permissionMessage": "Grant permission for full functionality", "permissionAllow": "Allow", "permissionDeny": "Deny", "deleteSkillTitle": "Delete skill", "deleteSkillConfirm": "Delete «{{name}}»?", "deleteSkill": "Delete", "cancelAction": "Cancel", "apiFormatOllama": "POST /api/chat · No auth", "apiFormatKobold": "POST /v1/chat/completions · No auth", "errorFallback": "Error"},
    "messageBubble": {"copied": "Copied", "copy": "Copy"},
    "usageChart": {"noData": "No data for the last few days", "outputTokens": "output", "inputTokens": "input", "daySun": "Sun", "dayMon": "Mon", "dayTue": "Tue", "dayWed": "Wed", "dayThu": "Thu", "dayFri": "Fri", "daySat": "Sat"},
    "quickActions": {"code": "Code", "codePrompt": "Write code", "plan": "Plan", "planPrompt": "Make a plan", "explanation": "Explanation", "explanationPrompt": "Explain", "fix": "Fix", "fixPrompt": "Fix the bug"},
    "sandbox": {"newSandbox": "Sandbox {{count}}", "sandboxes": "Sandboxes", "noContent": "No content", "noContentHint": "Ask the agent to write code — the result will appear here", "hasFiles": "Files available: select to preview", "filesTitle": "Sandbox files", "noFiles": "No files yet", "noFilesHint": "Ask the agent to create files via sandbox_write_file", "sectionHeader": "SANDBOXES", "noSandboxes": "No sandboxes", "noSandboxesHint": "A sandbox is a separate environment where the agent can run code, create HTML pages and SVG.", "createButton": "New sandbox"},
    "workspace": {"welcomeTitle": "How can I help?", "connectHint": "Set up connection", "inputPlaceholder": "Ask Agent…", "tokenInput": "In:", "tokenOutput": "Out:", "connected": "Connected", "notConfigured": "Not configured", "searchPlaceholder": "Search history...", "enterQuery": "Enter query", "searchHint": "Start typing to search chat history.", "nothingFound": "Nothing found", "tryChangeQuery": "Try changing the query.", "searchResults": "SEARCH RESULTS", "match": "match", "navigation": "NAVIGATION", "newChat": "New chat", "search": "Search", "library": "Library", "sandbox": "Sandbox", "recent": "RECENT", "noChatsYet": "No chats yet", "firstChatHint": "First chat will be created automatically after sending a message.", "messagesCount": "{{count}} msgs", "workspaceFiles": "Workspace files", "noActiveChat": "No active chat", "createChatHint": "Create a chat to see the workspace.", "exportArchive": "Export archive", "workspaceEmpty": "Workspace is empty", "saveFileHint": "Ask AI to save a file and it will appear here.", "selectModel": "Select model", "searchModel": "Search…", "loadingModels": "Loading models…", "loadError": "Loading error", "noModels": "No models", "camera": "Camera", "photo": "Photo", "files": "Files", "fileManager": "File manager", "contacts": "Contacts", "internetOn": "Internet: on", "internetOff": "Internet: off", "deleteChatTitle": "Delete chat?", "deleteChatMessage": "Dialog will be deleted without recovery.", "cancel": "Cancel", "delete": "Delete", "unknownRequestError": "Unknown request error", "imageNotSupported": "This model does not support images. Remove the photo from the message or choose another model.", "errorPrefix": "Error:", "otherProvider": "Other"}
}

# Language definitions with translations
languages = {
    "zh": {
        "name": "中文",
        "translations": {
            "common": {"loading": "加载中…", "error": "错误", "cancel": "取消", "ok": "确定", "delete": "删除", "save": "保存"},
            "status": {"idle": "就绪", "thinking": "思考中…", "error": "错误"},
            "agentStatus": {"modelNotSet": "未设置模型", "connectionNotConfigured": "未配置连接", "keySet": "已设置密钥", "noKey": "无密钥", "messages": "条消息"},
            "fileManager": {"previewTruncated": "\n\n[预览已截断：显示前 {{count}} 个字符]", "attachTruncated": "\n\n[文件附加时已截断：发送前 {{count}} 个字符]", "folderReadError": "读取文件夹失败", "bigFileTitle": "大文件", "bigFilePreview": "文件 {{size}}，仅显示开头部分进行预览", "unsupportedFile": "不支持的文件", "notUtf8": "无法以 UTF-8 文本读取文件", "fileReadError": "读取文件失败", "fileOpenError": "打开文件失败", "binaryNotSupported": "二进制文件不能作为文本附加", "bigFileAttach": "文件 {{size}}，将附加缩短的文本版本", "notUtf8Attach": "无法以 UTF-8 文本读取文件，因此不会附加", "attachReadError": "读取附件文件失败", "deleteTitle": "删除", "deleteConfirm": "删除「{{name}}」？", "cancel": "取消", "delete": "删除", "deleteError": "删除失败", "appData": "应用数据", "downloads": "下载", "photos": "照片", "documents": "文档", "files": "文件", "searchPlaceholder": "搜索文件…", "folderEmpty": "文件夹为空"},
            "settings": {"language": "语言", "model": "模型", "apiFormat": "API 格式", "connection": "连接", "provider": "提供商", "custom": "自定义", "noKey": "无密钥", "token": "令牌", "keyOptional": "密钥（可选）", "loading": "加载中…", "endpointHint1": "如果端点不需要密钥，请留空", "endpointHint2": "此提供商的授权令牌", "endpointHint3": "如果不需要授权，请留空", "permissions": "权限", "contactsAccess": "助手联系人访问", "contactsHint": "即使启用，通话和短信仍需单独确认", "androidPermissions": "Android 权限", "checkingPermissions": "检查权限中…", "stats": "统计", "inputTokens": "输入", "outputTokens": "输出", "totalTokens": "总计", "requests": "请求", "usageChart": "使用图表", "resetStatsButton": "重置统计", "update": "更新", "currentVersion": "当前版本", "updateHint": "Argus · 检查 GitHub 发布", "checkingUpdates": "检查更新中…", "checkUpdates": "检查更新", "updateAvailable": "有可用更新", "downloadInstall": "下载并安装", "downloading": "加载中…", "apkDownloaded": "APK 已下载，打开文件以安装", "retry": "重试", "skills": "技能", "noSkills": "无已保存技能", "skillsHint": "技能在 AI 解决复杂任务时自动创建", "usedCount": "已使用 {{count}} 次", "settingsTitle": "设置", "resetStatsTitle": "重置统计", "resetStatsMessage": "重置令牌计数器？", "resetStatsConfirm": "重置", "noUpdates": "无更新", "noUpdatesHint": "您已是最新版本", "checkError": "检查错误", "downloadError": "下载错误", "permissionTitle": "权限", "permissionMessage": "授予权限以获得完整功能", "permissionAllow": "允许", "permissionDeny": "拒绝", "deleteSkillTitle": "删除技能", "deleteSkillConfirm": "删除「{{name}}」？", "deleteSkill": "删除", "cancelAction": "取消", "apiFormatOllama": "POST /api/chat · 无认证", "apiFormatKobold": "POST /v1/chat/completions · 无认证", "errorFallback": "错误"},
            "messageBubble": {"copied": "已复制", "copy": "复制"},
            "usageChart": {"noData": "最近几天没有数据", "outputTokens": "输出", "inputTokens": "输入", "daySun": "周日", "dayMon": "周一", "dayTue": "周二", "dayWed": "周三", "dayThu": "周四", "dayFri": "周五", "daySat": "周六"},
            "quickActions": {"code": "代码", "codePrompt": "编写代码", "plan": "计划", "planPrompt": "制定计划", "explanation": "解释", "explanationPrompt": "解释", "fix": "修复", "fixPrompt": "修复错误"},
            "sandbox": {"newSandbox": "沙盒 {{count}}", "sandboxes": "沙盒", "noContent": "无内容", "noContentHint": "让助手编写代码 — 结果将显示在此处", "hasFiles": "有可用文件：选择以预览", "filesTitle": "沙盒文件", "noFiles": "暂无文件", "noFilesHint": "让助手通过 sandbox_write_file 创建文件", "sectionHeader": "沙盒", "noSandboxes": "无沙盒", "noSandboxesHint": "沙盒是助手可以运行代码、创建 HTML 页面和 SVG 的独立环境", "createButton": "新建沙盒"},
            "workspace": {"welcomeTitle": "我能帮您什么？", "connectHint": "设置连接", "inputPlaceholder": "询问助手…", "tokenInput": "输入：", "tokenOutput": "输出：", "connected": "已连接", "notConfigured": "未配置", "searchPlaceholder": "搜索历史…", "enterQuery": "输入查询", "searchHint": "开始输入以搜索聊天历史", "nothingFound": "未找到", "tryChangeQuery": "请尝试修改查询", "searchResults": "搜索结果", "match": "匹配", "navigation": "导航", "newChat": "新聊天", "search": "搜索", "library": "库", "sandbox": "沙盒", "recent": "最近", "noChatsYet": "暂无聊天", "firstChatHint": "发送消息后将自动创建第一个聊天", "messagesCount": "{{count}} 条消息", "workspaceFiles": "工作区文件", "noActiveChat": "无活跃聊天", "createChatHint": "创建聊天以查看工作区", "exportArchive": "导出归档", "workspaceEmpty": "工作区为空", "saveFileHint": "让 AI 保存文件，它将显示在此处", "selectModel": "选择模型", "searchModel": "搜索…", "loadingModels": "加载模型中…", "loadError": "加载错误", "noModels": "无模型", "camera": "相机", "photo": "照片", "files": "文件", "fileManager": "文件管理器", "contacts": "联系人", "internetOn": "互联网：开", "internetOff": "互联网：关", "deleteChatTitle": "删除聊天？", "deleteChatMessage": "对话将被删除且无法恢复", "cancel": "取消", "delete": "删除", "unknownRequestError": "未知请求错误", "imageNotSupported": "此模型不支持图片。请从消息中删除照片或选择其他模型", "errorPrefix": "错误：", "otherProvider": "其他"}
        }
    },
    "hi": {
        "name": "हिन्दी",
        "translations": {
            "common": {"loading": "लोड हो रहा है…", "error": "त्रुटि", "cancel": "रद्द करें", "ok": "ठीक है", "delete": "हटाएं", "save": "सहेजें"},
            "status": {"idle": "तैयार", "thinking": "सोच रहा है…", "error": "त्रुटि"},
            "agentStatus": {"modelNotSet": "मॉडल सेट नहीं है", "connectionNotConfigured": "कनेक्शन कॉन्फ़िगर नहीं है", "keySet": "कुंजी सेट है", "noKey": "कोई कुंजी नहीं", "messages": "संदेश"},
            "fileManager": {"previewTruncated": "\n\n[पूर्वावलोकन छोटा किया गया: पहले {{count}} अक्षर दिखाए जा रहे हैं]", "attachTruncated": "\n\n[संलग्न करते समय फ़ाइल छोटी की गई: पहले {{count}} अक्षर भेजे गए]", "folderReadError": "फ़ोल्डर पढ़ने में विफल", "bigFileTitle": "बड़ी फ़ाइल", "bigFilePreview": "फ़ाइल {{size}}। केवल शुरुआत दिखाई जाएगी", "unsupportedFile": "असमर्थित फ़ाइल", "notUtf8": "फ़ाइल को UTF-8 टेक्स्ट के रूप में नहीं पढ़ा जा सका", "fileReadError": "फ़ाइल पढ़ने में विफल", "fileOpenError": "फ़ाइल खोलने में विफल", "binaryNotSupported": "बाइनरी फ़ाइलों को टेक्स्ट के रूप में संलग्न नहीं किया जा सकता", "bigFileAttach": "फ़ाइल {{size}}। केवल छोटा टेक्स्ट संस्करण संलग्न होगा", "notUtf8Attach": "फ़ाइल को UTF-8 टेक्स्ट के रूप में नहीं पढ़ा जा सका, इसलिए संलग्न नहीं होगी", "attachReadError": "संलग्न के लिए फ़ाइल पढ़ने में विफल", "deleteTitle": "हटाएं", "deleteConfirm": "«{{name}}» हटाएं?", "cancel": "रद्द करें", "delete": "हटाएं", "deleteError": "हटाने में विफल", "appData": "ऐप डेटा", "downloads": "डाउनलोड", "photos": "फ़ोटो", "documents": "दस्तावेज़", "files": "फ़ाइलें", "searchPlaceholder": "फ़ाइलें खोजें…", "folderEmpty": "फ़ोल्डर खाली है"},
            "settings": {"language": "भाषा", "model": "मॉडल", "apiFormat": "API प्रारूप", "connection": "कनेक्शन", "provider": "प्रदाता", "custom": "कस्टम", "noKey": "कोई कुंजी नहीं", "token": "टोकन", "keyOptional": "कुंजी (वैकल्पिक)", "loading": "लोड हो रहा है…", "endpointHint1": "यदि एंडपॉइंट को कुंजी की आवश्यकता नहीं है तो खाली छोड़ें", "endpointHint2": "इस प्रदाता के लिए प्राधिकरण टोकन", "endpointHint3": "यदि प्राधिकरण की आवश्यकता नहीं है तो खाली छोड़ें", "permissions": "अनुमतियाँ", "contactsAccess": "सहायक संपर्क पहुँच", "contactsHint": "सक्षम होने पर भी, कॉल और SMS के लिए अलग पुष्टि आवश्यक है", "androidPermissions": "Android अनुमतियाँ", "checkingPermissions": "अनुमतियाँ जाँच रहे हैं…", "stats": "आंकड़े", "inputTokens": "इनपुट", "outputTokens": "आउटपुट", "totalTokens": "कुल", "requests": "अनुरोध", "usageChart": "उपयोग चार्ट", "resetStatsButton": "आंकड़े रीसेट करें", "update": "अपडेट", "currentVersion": "वर्तमान संस्करण", "updateHint": "Argus · GitHub रिलीज़ जाँचता है", "checkingUpdates": "अपडेट जाँच रहे हैं…", "checkUpdates": "अपडेट जाँचें", "updateAvailable": "अपडेट उपलब्ध है", "downloadInstall": "डाउनलोड और इंस्टॉल करें", "downloading": "लोड हो रहा है…", "apkDownloaded": "APK डाउनलोड हो गया। इंस्टॉल के लिए फ़ाइल खोलें", "retry": "पुनः प्रयास करें", "skills": "कौशल", "noSkills": "कोई सहेजा गया कौशल नहीं", "skillsHint": "कौशल AI द्वारा जटिल कार्य हल करने पर स्वचालित रूप से बनते हैं", "usedCount": "{{count}} बार उपयोग किया गया", "settingsTitle": "सेटिंग्स", "resetStatsTitle": "आंकड़े रीसेट करें", "resetStatsMessage": "टोकन काउंटर रीसेट करें?", "resetStatsConfirm": "रीसेट करें", "noUpdates": "कोई अपडेट नहीं", "noUpdatesHint": "आपके पास नवीनतम संस्करण है", "checkError": "जाँच त्रुटि", "downloadError": "डाउनलोड त्रुटि", "permissionTitle": "अनुमति", "permissionMessage": "पूर्ण कार्यक्षमता के लिए अनुमति दें", "permissionAllow": "अनुमति दें", "permissionDeny": "अस्वीकार करें", "deleteSkillTitle": "कौशल हटाएं", "deleteSkillConfirm": "«{{name}}» हटाएं?", "deleteSkill": "हटाएं", "cancelAction": "रद्द करें", "apiFormatOllama": "POST /api/chat · कोई प्रमाणीकरण नहीं", "apiFormatKobold": "POST /v1/chat/completions · कोई प्रमाणीकरण नहीं", "errorFallback": "त्रुटि"},
            "messageBubble": {"copied": "कॉपी किया गया", "copy": "कॉपी करें"},
            "usageChart": {"noData": "पिछले कुछ दिनों में कोई डेटा नहीं", "outputTokens": "आउटपुट", "inputTokens": "इनपुट", "daySun": "रवि", "dayMon": "सोम", "dayTue": "मंगल", "dayWed": "बुध", "dayThu": "गुरु", "dayFri": "शुक्र", "daySat": "शनि"},
            "quickActions": {"code": "कोड", "codePrompt": "कोड लिखें", "plan": "योजना", "planPrompt": "योजना बनाएं", "explanation": "व्याख्या", "explanationPrompt": "समझाएं", "fix": "ठीक करें", "fixPrompt": "बग ठीक करें"},
            "sandbox": {"newSandbox": "सैंडबॉक्स {{count}}", "sandboxes": "सैंडबॉक्स", "noContent": "कोई सामग्री नहीं", "noContentHint": "एजेंट से कोड लिखने के लिए कहें — परिणाम यहाँ दिखाई देगा", "hasFiles": "फ़ाइलें उपलब्ध हैं: पूर्वावलोकन के लिए चुनें", "filesTitle": "सैंडबॉक्स फ़ाइलें", "noFiles": "अभी कोई फ़ाइल नहीं", "noFilesHint": "एजेंट से sandbox_write_file के माध्यम से फ़ाइलें बनाने के लिए कहें", "sectionHeader": "सैंडबॉक्स", "noSandboxes": "कोई सैंडबॉक्स नहीं", "noSandboxesHint": "सैंडबॉक्स एक अलग वातावरण है जहाँ एजेंट कोड चला सकता है, HTML पृष्ठ और SVG बना सकता है", "createButton": "नया सैंडबॉक्स"},
            "workspace": {"welcomeTitle": "मैं आपकी कैसे मदद कर सकता हूँ?", "connectHint": "कनेक्शन सेट करें", "inputPlaceholder": "एजेंट से पूछें…", "tokenInput": "इनपुट:", "tokenOutput": "आउटपुट:", "connected": "कनेक्टेड", "notConfigured": "कॉन्फ़िगर नहीं है", "searchPlaceholder": "इतिहास खोजें…", "enterQuery": "प्रश्न दर्ज करें", "searchHint": "चैट इतिहास खोजने के लिए टाइप करना शुरू करें", "nothingFound": "कुछ नहीं मिला", "tryChangeQuery": "प्रश्न बदलकर देखें", "searchResults": "खोज परिणाम", "match": "मिलान", "navigation": "नेविगेशन", "newChat": "नया चैट", "search": "खोजें", "library": "लाइब्रेरी", "sandbox": "सैंडबॉक्स", "recent": "हाल का", "noChatsYet": "अभी कोई चैट नहीं", "firstChatHint": "संदेश भेजने के बाद पहला चैट स्वचालित रूप से बन जाएगा", "messagesCount": "{{count}} संदेश", "workspaceFiles": "वर्कस्पेस फ़ाइलें", "noActiveChat": "कोई सक्रिय चैट नहीं", "createChatHint": "वर्कस्पेस देखने के लिए चैट बनाएं", "exportArchive": "आर्काइव निर्यात करें", "workspaceEmpty": "वर्कस्पेस खाली है", "saveFileHint": "AI से फ़ाइल सहेजने के लिए कहें, वह यहाँ दिखाई देगी", "selectModel": "मॉडल चुनें", "searchModel": "खोजें…", "loadingModels": "मॉडल लोड हो रहे हैं…", "loadError": "लोड त्रुटि", "noModels": "कोई मॉडल नहीं", "camera": "कैमरा", "photo": "फ़ोटो", "files": "फ़ाइलें", "fileManager": "फ़ाइल प्रबंधक", "contacts": "संपर्क", "internetOn": "इंटरनेट: चालू", "internetOff": "इंटरनेट: बंद", "deleteChatTitle": "चैट हटाएं?", "deleteChatMessage": "संवाद बिना रिकवरी के हटा दिया जाएगा", "cancel": "रद्द करें", "delete": "हटाएं", "unknownRequestError": "अज्ञात अनुरोध त्रुटि", "imageNotSupported": "यह मॉडल चित्रों का समर्थन नहीं करता। संदेश से फ़ोटो हटाएं या अन्य मॉडल चुनें", "errorPrefix": "त्रुटि:", "otherProvider": "अन्य"}
        }
    },
    "es": {
        "name": "Español",
        "translations": {
            "common": {"loading": "Cargando…", "error": "Error", "cancel": "Cancelar", "ok": "Aceptar", "delete": "Eliminar", "save": "Guardar"},
            "status": {"idle": "Listo", "thinking": "Pensando…", "error": "Error"},
            "agentStatus": {"modelNotSet": "Modelo no configurado", "connectionNotConfigured": "Conexión no configurada", "keySet": "clave establecida", "noKey": "sin clave", "messages": "mensajes"},
            "fileManager": {"previewTruncated": "\n\n[Vista previa truncada: mostrando primeros {{count}} caracteres]", "attachTruncated": "\n\n[Archivo truncado al adjuntar: primeros {{count}} caracteres enviados]", "folderReadError": "Error al leer carpeta", "bigFileTitle": "Archivo grande", "bigFilePreview": "Archivo {{size}}. Solo se mostrará el inicio para vista previa", "unsupportedFile": "Formato no soportado", "notUtf8": "No se pudo leer el archivo como texto UTF-8", "fileReadError": "Error al leer archivo", "fileOpenError": "Error al abrir archivo", "binaryNotSupported": "Los archivos binarios no se pueden adjuntar como texto", "bigFileAttach": "Archivo {{size}}. Solo se adjuntará una versión de texto acortada", "notUtf8Attach": "No se pudo leer el archivo como texto UTF-8, no se adjuntará", "attachReadError": "Error al leer archivo para adjuntar", "deleteTitle": "Eliminar", "deleteConfirm": "¿Eliminar «{{name}}»?", "cancel": "Cancelar", "delete": "Eliminar", "deleteError": "Error al eliminar", "appData": "Datos de la app", "downloads": "Descargas", "photos": "Fotos", "documents": "Documentos", "files": "Archivos", "searchPlaceholder": "Buscar archivos…", "folderEmpty": "La carpeta está vacía"},
            "settings": {"language": "Idioma", "model": "Modelo", "apiFormat": "Formato API", "connection": "CONEXIÓN", "provider": "Proveedor", "custom": "Personalizado", "noKey": "Sin clave", "token": "Token", "keyOptional": "Clave (opcional)", "loading": "Cargando…", "endpointHint1": "Déjelo vacío si el endpoint no requiere clave", "endpointHint2": "Token de autorización para este proveedor", "endpointHint3": "Déjelo vacío si no se requiere autorización", "permissions": "PERMISOS", "contactsAccess": "Acceso a contactos del asistente", "contactsHint": "Aunque esté habilitado, las llamadas y SMS requieren confirmación separada", "androidPermissions": "Permisos de Android", "checkingPermissions": "Verificando permisos…", "stats": "ESTADÍSTICAS", "inputTokens": "entrada", "outputTokens": "salida", "totalTokens": "total", "requests": "solicitudes", "usageChart": "Gráfico de uso", "resetStatsButton": "Restablecer estadísticas", "update": "ACTUALIZACIÓN", "currentVersion": "Versión actual", "updateHint": "Argus · Verifica lanzamientos de GitHub", "checkingUpdates": "Buscando actualizaciones…", "checkUpdates": "Buscar actualizaciones", "updateAvailable": "Actualización disponible", "downloadInstall": "Descargar e instalar", "downloading": "Cargando…", "apkDownloaded": "APK descargado. Abra el archivo para instalar", "retry": "Reintentar", "skills": "HABILIDADES", "noSkills": "Sin habilidades guardadas", "skillsHint": "Las habilidades se crean automáticamente cuando la IA resuelve tareas complejas", "usedCount": "usado {{count}} veces", "settingsTitle": "Configuración", "resetStatsTitle": "Restablecer estadísticas", "resetStatsMessage": "¿Restablecer contadores de tokens?", "resetStatsConfirm": "Restablecer", "noUpdates": "Sin actualizaciones", "noUpdatesHint": "Tiene la última versión", "checkError": "Error de verificación", "downloadError": "Error de descarga", "permissionTitle": "Permiso", "permissionMessage": "Otorgue permiso para funcionalidad completa", "permissionAllow": "Permitir", "permissionDeny": "Denegar", "deleteSkillTitle": "Eliminar habilidad", "deleteSkillConfirm": "¿Eliminar «{{name}}»?", "deleteSkill": "Eliminar", "cancelAction": "Cancelar", "apiFormatOllama": "POST /api/chat · Sin auth", "apiFormatKobold": "POST /v1/chat/completions · Sin auth", "errorFallback": "Error"},
            "messageBubble": {"copied": "Copiado", "copy": "Copiar"},
            "usageChart": {"noData": "Sin datos de los últimos días", "outputTokens": "salida", "inputTokens": "entrada", "daySun": "Dom", "dayMon": "Lun", "dayTue": "Mar", "dayWed": "Mié", "dayThu": "Jue", "dayFri": "Vie", "daySat": "Sáb"},
            "quickActions": {"code": "Código", "codePrompt": "Escribir código", "plan": "Plan", "planPrompt": "Hacer un plan", "explanation": "Explicación", "explanationPrompt": "Explicar", "fix": "Corregir", "fixPrompt": "Corregir el error"},
            "sandbox": {"newSandbox": "Sandbox {{count}}", "sandboxes": "Sandboxes", "noContent": "Sin contenido", "noContentHint": "Pida al asistente que escriba código — el resultado aparecerá aquí", "hasFiles": "Archivos disponibles: seleccione para vista previa", "filesTitle": "Archivos del sandbox", "noFiles": "Aún no hay archivos", "noFilesHint": "Pida al asistente crear archivos mediante sandbox_write_file", "sectionHeader": "SANDBOXES", "noSandboxes": "Sin sandboxes", "noSandboxesHint": "Un sandbox es un entorno separado donde el asistente puede ejecutar código, crear páginas HTML y SVG", "createButton": "Nuevo sandbox"},
            "workspace": {"welcomeTitle": "¿Cómo puedo ayudarle?", "connectHint": "Configurar conexión", "inputPlaceholder": "Pregunte al asistente…", "tokenInput": "Entrada:", "tokenOutput": "Salida:", "connected": "Conectado", "notConfigured": "No configurado", "searchPlaceholder": "Buscar historial…", "enterQuery": "Ingrese consulta", "searchHint": "Comience a escribir para buscar en el historial de chats", "nothingFound": "Nada encontrado", "tryChangeQuery": "Intente cambiar la consulta", "searchResults": "RESULTADOS DE BÚSQUEDA", "match": "coincidencia", "navigation": "NAVEGACIÓN", "newChat": "Nuevo chat", "search": "Buscar", "library": "Biblioteca", "sandbox": "Sandbox", "recent": "RECIENTE", "noChatsYet": "Aún no hay chats", "firstChatHint": "El primer chat se creará automáticamente después de enviar un mensaje", "messagesCount": "{{count}} mensajes", "workspaceFiles": "Archivos del área de trabajo", "noActiveChat": "Sin chat activo", "createChatHint": "Cree un chat para ver el área de trabajo", "exportArchive": "Exportar archivo", "workspaceEmpty": "El área de trabajo está vacía", "saveFileHint": "Pida a la IA guardar un archivo y aparecerá aquí", "selectModel": "Seleccionar modelo", "searchModel": "Buscar…", "loadingModels": "Cargando modelos…", "loadError": "Error de carga", "noModels": "Sin modelos", "camera": "Cámara", "photo": "Foto", "files": "Archivos", "fileManager": "Gestor de archivos", "contacts": "Contactos", "internetOn": "Internet: activado", "internetOff": "Internet: desactivado", "deleteChatTitle": "¿Eliminar chat?", "deleteChatMessage": "El diálogo se eliminará sin recuperación", "cancel": "Cancelar", "delete": "Eliminar", "unknownRequestError": "Error de solicitud desconocido", "imageNotSupported": "Este modelo no soporta imágenes. Elimine la foto del mensaje o elija otro modelo", "errorPrefix": "Error:", "otherProvider": "Otro"}
        }
    }
}

# Save files
locales_dir = r'H:\argus\apps\argus-mobile\assets\locales'

for lang_code, lang_data in languages.items():
    filepath = os.path.join(locales_dir, f'{lang_code}.json')
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(lang_data['translations'], f, ensure_ascii=False, indent=2)
    print(f'Created {lang_code}.json')

print(f'\nCreated {len(languages)} locale files')
