name: Build and Release - DEBUG

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (Required for node_modules)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace --info
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64